[package]
name = "bitcoin_ath"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.41", features = ["full"] }
tokio-cron-scheduler = "0.13"
